#!/usr/bin/env bash
set -euo pipefail

if [[ $# -ne 2 ]]; then
  echo "usage: $0 <flavor> <output-config>" >&2
  exit 2
fi

flavor="$1"
output_config="$2"

case "$flavor" in
  bootlin-musl)
    toolchain_symbols=(
      "BR2_TOOLCHAIN_EXTERNAL_BOOTLIN"
      "BR2_TOOLCHAIN_EXTERNAL_BOOTLIN_AARCH64_MUSL_STABLE"
    )
    libc="musl"
    target_tuple="aarch64-buildroot-linux-musl"
    ;;
  arm-glibc)
    toolchain_symbols=(
      "BR2_TOOLCHAIN_EXTERNAL_ARM_AARCH64"
    )
    libc="glibc"
    target_tuple="aarch64-none-linux-gnu"
    ;;
  *)
    echo "unsupported flavor: $flavor" >&2
    echo "supported flavors: bootlin-musl, arm-glibc" >&2
    exit 2
    ;;
esac

mkdir -p "$(dirname "$output_config")"
{
cat <<EOF_CONFIG
# Generated by scripts/make-prebuilt-config.sh for ${flavor}.
BR2_aarch64=y
BR2_cortex_a55=y
BR2_TOOLCHAIN_EXTERNAL=y
BR2_TOOLCHAIN_EXTERNAL_DOWNLOAD=y
EOF_CONFIG
for symbol in "${toolchain_symbols[@]}"; do
  printf '%s=y\n' "$symbol"
done
cat <<EOF_CONFIG
BR2_TARGET_GENERIC_GETTY_PORT="ttyS0"
BR2_INIT_NONE=y
BR2_SYSTEM_BIN_SH_NONE=y
BR2_PACKAGE_BUSYBOX=n
BR2_PER_PACKAGE_DIRECTORIES=y
BR2_CCACHE=y
BR2_CCACHE_DIR="~/.buildroot-ccache"
BR2_CCACHE_INITIAL_SETUP="--max-size=30G"
BR2_CCACHE_USE_BASEDIR=y
BR2_PACKAGE_LLVM=y
BR2_PACKAGE_LLVM_RTTI=y
BR2_PACKAGE_CLANG=y
BR2_PACKAGE_LIBCLC=y
BR2_PACKAGE_SPIRV_HEADERS=y
BR2_PACKAGE_SPIRV_TOOLS=y
BR2_PACKAGE_SPIRV_LLVM_TRANSLATOR=y
EOF_CONFIG
} >"$output_config"

cat >&2 <<EOF_INFO
Generated Buildroot config:
  flavor:       ${flavor}
  libc:         ${libc}
  target tuple: ${target_tuple}
  file:         ${output_config}
EOF_INFO
